title: Gyeol Rachel Han
description: 디자인 공부
theme: just-the-docs

url: https://gyeolhan.github.io/design-blog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
